# Generated by Django 2.0.1 on 2018-03-28 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserRegistration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='varsity_id',
        ),
    ]
