# Generated by Django 2.0.1 on 2018-04-10 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receivers_varsity_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mail_subject', models.CharField(blank=True, max_length=100, null=True)),
                ('sent_to', models.EmailField(max_length=254)),
                ('mail_body', models.TextField()),
                ('sent_time', models.TimeField(auto_now_add=True)),
                ('sent_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
