# Generated by Django 2.0.1 on 2018-03-23 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=50)),
                ('person_dob', models.DateField()),
                ('person_permanent_address', models.TextField()),
                ('person_present_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PersonalInfo.Person')),
                ('student_sec', models.CharField(max_length=2)),
                ('student_dept', models.CharField(max_length=5)),
            ],
            bases=('PersonalInfo.person',),
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PersonalInfo.Person')),
                ('teacher_initial', models.CharField(max_length=10)),
            ],
            bases=('PersonalInfo.person',),
        ),
    ]
