# Generated by Django 2.0.1 on 2018-03-28 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalInfo', '0003_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback',
            new_name='feedback_body',
        ),
    ]
