# Generated by Django 2.0.1 on 2018-03-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoutineManagement', '0002_auto_20180324_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routineinfo',
            name='slot1_course_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='routineinfo',
            name='slot2_course_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='routineinfo',
            name='slot3_course_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='routineinfo',
            name='slot4_course_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='routineinfo',
            name='slot5_course_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='routineinfo',
            name='slot6_course_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
