# Generated by Django 2.0.1 on 2018-04-14 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RoutineManagement', '0003_auto_20180328_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherRoutine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('slot1_room_no', models.CharField(blank=True, max_length=5, null=True)),
                ('slot1_course_name', models.CharField(blank=True, max_length=100, null=True)),
                ('slot1_course_code', models.CharField(blank=True, max_length=10, null=True)),
                ('slot2_room_no', models.CharField(blank=True, max_length=5, null=True)),
                ('slot2_course_name', models.CharField(blank=True, max_length=100, null=True)),
                ('slot2_course_code', models.CharField(blank=True, max_length=10, null=True)),
                ('slot3_room_no', models.CharField(blank=True, max_length=5, null=True)),
                ('slot3_course_name', models.CharField(blank=True, max_length=100, null=True)),
                ('slot3_course_code', models.CharField(blank=True, max_length=10, null=True)),
                ('slot4_room_no', models.CharField(blank=True, max_length=5, null=True)),
                ('slot4_course_name', models.CharField(blank=True, max_length=100, null=True)),
                ('slot4_course_code', models.CharField(blank=True, max_length=10, null=True)),
                ('slot5_room_no', models.CharField(blank=True, max_length=5, null=True)),
                ('slot5_course_name', models.CharField(blank=True, max_length=100, null=True)),
                ('slot5_course_code', models.CharField(blank=True, max_length=10, null=True)),
                ('slot6_room_no', models.CharField(blank=True, max_length=5, null=True)),
                ('slot6_course_name', models.CharField(blank=True, max_length=100, null=True)),
                ('slot6_course_code', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='routineinfo',
            name='slot1_room_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routineinfo',
            name='slot2_room_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routineinfo',
            name='slot3_room_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routineinfo',
            name='slot4_room_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routineinfo',
            name='slot5_room_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routineinfo',
            name='slot6_room_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
