# Generated by Django 2.0.1 on 2018-04-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoutineManagement', '0004_auto_20180415_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='routineinfo',
            name='slot1_section',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='routineinfo',
            name='slot2_section',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='routineinfo',
            name='slot3_section',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='routineinfo',
            name='slot4_section',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='routineinfo',
            name='slot5_section',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='routineinfo',
            name='slot6_section',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
