# Generated by Django 2.0.1 on 2018-04-04 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('slot1_teacher_initial', models.CharField(blank=True, max_length=5, null=True)),
                ('slot1_course_name', models.CharField(blank=True, max_length=100, null=True)),
                ('slot1_course_code', models.CharField(blank=True, max_length=10, null=True)),
                ('slot2_teacher_initial', models.CharField(blank=True, max_length=5, null=True)),
                ('slot2_course_name', models.CharField(blank=True, max_length=100, null=True)),
                ('slot2_course_code', models.CharField(blank=True, max_length=10, null=True)),
                ('slot3_teacher_initial', models.CharField(blank=True, max_length=5, null=True)),
                ('slot3_course_name', models.CharField(blank=True, max_length=100, null=True)),
                ('slot3_course_code', models.CharField(blank=True, max_length=10, null=True)),
                ('slot4_teacher_initial', models.CharField(blank=True, max_length=5, null=True)),
                ('slot4_course_name', models.CharField(blank=True, max_length=100, null=True)),
                ('slot4_course_code', models.CharField(blank=True, max_length=10, null=True)),
                ('slot5_teacher_initial', models.CharField(blank=True, max_length=5, null=True)),
                ('slot5_course_name', models.CharField(blank=True, max_length=100, null=True)),
                ('slot5_course_code', models.CharField(blank=True, max_length=10, null=True)),
                ('slot6_teacher_initial', models.CharField(blank=True, max_length=5, null=True)),
                ('slot6_course_name', models.CharField(blank=True, max_length=100, null=True)),
                ('slot6_course_code', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
